name: relayered
description: A new Flutter project.

publish_to: 'none'
version: 1.0.7

environment:
  sdk: ">=3.0.0 <=4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #Services
  awesome_notifications: any
  intl: any
  shared_preferences: any

  #UI
  flutter_quill: any
  flutter_quill_extensions: any


  #Firebase
  encrypt: any
  firebase_auth: any
  cloud_firestore: any
  firebase_core: any 

dev_dependencies:
  flutter_launcher_icons: any
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  #    flutter pub run flutter_launcher_icons:main
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf

    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

    - family: JetBrainsMono
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf

    - family: IBMPlexMono
      fonts:
        - asset: fonts/IBMPlexMono-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
        
  assets:
    - assets/translations/

